repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.3
    hooks:
      - id: terraform_fmt
        files: \.(tf|tfvars|tftest\.hcl)$
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/terraform/.tflint.hcl
        files: \.tf$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files # Default is fail on files larger than 500kB
      - id: mixed-line-ending
        args: [--fix=lf] # Ensure all line endings are LF
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
